### ISSUE TITLE
生成的二维码扫描登录不上

### ISSUE THREAD

**Issue by lanjy1024** [ersaijun/play_with_wechat#1]
你好呀，请问生成的二维码扫描登录不上怎么办

**Comment by ersaijun** [comment]
什么错误？

**Comment by lanjy1024** [comment]
谢谢大佬的回复
是这样的，输入数字1之后显示这样的二维码，
感觉这个二维码并不完整，我装的python版本是3.8的，不知道是不是python版本的问题，我在换一个2.7版本的试试





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kaspar.S"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月7日(星期二) 晚上6:10
收件人:&nbsp;"ersaijun/play_with_wechat"<play_with_wechat@noreply.github.com&gt;;
抄送:&nbsp;"AirBall"<1615960786@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ersaijun/play_with_wechat] 生成的二维码扫描登录不上 (#1)




什么错误？

**Comment by ersaijun** [comment]
用命令行运行，在vscode等编译器中debug确实会出现二维码错位不完整的情况，我出现过。
在命令窗口用python main.py运行可避免

**Comment by wu-feng20** [comment]
登不上网页微信怎么破
